name: Deploy Ethra AI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ethra-ai

    env:
      GO_VERSION: "1.22.6"
      APP_NAME: "ethra-go"
      TARGET_DIR: "/opt/ethra-go"
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: "3000"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: "gpt-4o-mini"
      OPENAI_TIMEOUT: "120000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build
        run: go build -o ${{ env.APP_NAME }} ./cmd/server

      # Debug steps start here
      - name: Debug environment variables
        run: |
          echo "SERVER_USER: ${SERVER_USER:+set}"
          echo "SERVER_HOST: ${SERVER_HOST:+set}"
          echo "SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY:+set}"
          echo "OPENAI_API_KEY: ${OPENAI_API_KEY:+set}"

      - name: Check SSH connection details
        run: |
          echo "Attempting SSH connection..."
          ssh -o StrictHostKeyChecking=no -i <(echo "${SSH_PRIVATE_KEY}") ${SERVER_USER}@${SERVER_HOST} exit || echo "SSH connection failed"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Stopping old app..."
            sudo systemctl stop ethra-go || true

            echo "Uploading new binary..."
            scp -o StrictHostKeyChecking=no ${{ env.APP_NAME }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.TARGET_DIR }}/

            echo "Creating .env file..."
            cat > '${{ env.TARGET_DIR }}/.env' <<EOL
            PORT=${{ env.PORT }}
            OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
            OPENAI_MODEL=${{ env.OPENAI_MODEL }}
            OPENAI_TIMEOUT=${{ env.OPENAI_TIMEOUT }}
            EOL

            echo "Starting app..."
            sudo systemctl daemon-reload
            sudo systemctl start ethra-go
            sudo systemctl status ethra-go --no-pager
