name: Deploy Ethra AI Service

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ethra-ai

    env:
      GO_VERSION: "1.22.6"
      APP_NAME: "ethra-go"
      TARGET_DIR: "/opt/ethra-go"
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: "3000"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: "gpt-4o-mini"
      OPENAI_TIMEOUT: "120000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      - name: Build binary
        run: go build -o ${{ env.APP_NAME }} ./cmd/server

      - name: Create .env locally
        run: |
          cat > .env <<EOF
PORT=${{ env.PORT }}
OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
OPENAI_MODEL=${{ env.OPENAI_MODEL }}
OPENAI_TIMEOUT=${{ env.OPENAI_TIMEOUT }}
EOF
          echo ".env contents:"
          sed -n '1,200p' .env

      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SSH connection test OK on $(hostname)"

      - name: Upload binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          source: ${{ env.APP_NAME }}
          target: ${{ env.TARGET_DIR }}

      - name: Upload .env to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          source: .env
          target: ${{ env.TARGET_DIR }}

      - name: Remote post-deploy (permissions & systemd restart)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Stopping old service (if exists)..."
            sudo systemctl stop ethra-go || true

            echo "Ensuring target directory exists..."
            sudo mkdir -p ${{ env.TARGET_DIR }}
            sudo chown -R ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.TARGET_DIR }}

            echo "Make binary executable and set ownership..."
            sudo chmod +x ${{ env.TARGET_DIR }}/${{ env.APP_NAME }}
            sudo chown ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.TARGET_DIR }}/${{ env.APP_NAME }}

            echo "Ensure .env exists and set ownership..."
            sudo chown ${{ env.SERVER_USER }}:${{ env.SERVER_USER }} ${{ env.TARGET_DIR }}/.env
            sudo chmod 600 ${{ env.TARGET_DIR }}/.env

            echo "Reload systemd and restart service..."
            sudo systemctl daemon-reload
            sudo systemctl enable ethra-go || true
            sudo systemctl restart ethra-go
            sudo systemctl status ethra-go --no-pager
